name: Validate PR target

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize, edited]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Validate source branch
        shell: bash
        run: |
          HEAD="${{ github.event.pull_request.head.ref }}"

          echo "Head: $HEAD"

          if [[ "$HEAD" != "develop" && "$HEAD" != hotfix/* && "$HEAD" != release/* ]]; then
            echo "Only develop, hotfix/* and release/* branches can be merged into master."
            exit 1
          fi
